Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
// Seção de Declarações das variáveis 
 a,b,c,d: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("DIGITE TRES NUMEROS:")
 leia(a,c,b)
 d <- a+c-b
 escreva("O RESULTADO É" ,d)

Fimalgoritmo