Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
// Seção de Declarações das variáveis 
a,s: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("escreva um numero inteiro: ")
leia (a)
s <- a/2
escreva("A METADE DE " ,a, " É" ,s)

Fimalgoritmo